apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          io.kompose.network/mysql: "true"
  podSelector:
    matchLabels:
      io.kompose.network/mysql: "true"
